//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FamilyDB> FamilyDBs { get; set; }
        public virtual DbSet<login> logins { get; set; }
        public virtual DbSet<NannyData> NannyDatas { get; set; }
        public virtual DbSet<WorkChart> WorkCharts { get; set; }
        public virtual DbSet<Notifi> Notifis { get; set; }
        public virtual DbSet<WorkTable> WorkTables { get; set; }
        public virtual DbSet<AdmintoNannyReq> AdmintoNannyReqs { get; set; }
    }
}
