//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyDB
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public string NationalID { get; set; }
        public byte[] NIDPic { get; set; }
        public string Gander { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}
